vich_uploader:
    db_driver: orm

    mappings:
        thumbnail:
           uri_prefix: /images/thumbnails
           upload_destination: '%kernel.project_dir%/public/images/thumbnails'
        news_images:
            uri_prefix: '%app.path.news_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.news_images%'
